--Criação de Banco de dados.
create database N8_Ex01
--conecta a uma base de dados já criada
use N8_Ex01

create table usuario
(
	id_usuario int not null identity primary key,
	nome_usuario varchar(50) not null,
	cpf_usuario char(14) not null unique,
	login_usuario varchar(50) not null unique,
	senha_usuario varchar(50) not null,
	email_usuario varchar(50) not null unique,
	obs_usuario varchar(255) null,
	status_usuario varchar(25) not null
)
select * from usuario
	

-- cadastrar valores na Tabela
insert into usuario 
	(nome_usuario,cpf_usuario,login_usuario,senha_usuario,email_usuario,obs_usuario,status_usuario)
values
	('Administrador','111.111.111-11','admin','123','admin@admin.com','','Ativo')

insert into usuario 
	(nome_usuario,cpf_usuario,login_usuario,senha_usuario,email_usuario,obs_usuario,status_usuario)
values
	('Benegundes','111.111.111-12','benegundes','123','benegundes@admin.com','','Ativo')

insert into usuario 
	(nome_usuario,cpf_usuario,login_usuario,senha_usuario,email_usuario,obs_usuario,status_usuario)
values
	('Asdrubal','111.111.111-13','asdrubal','123','asdrubal@admin.com','','Ativo'),
	('Judith','111.111.111-14','judith','123','judith@admin.com','','Ativo')

insert into usuario 
	(nome_usuario,cpf_usuario,login_usuario,senha_usuario,email_usuario,obs_usuario,status_usuario)
values
	('Jeremias','111.111.111-15','jeremias','123','jeremias@admin.com','','Ativo')

update usuario set senha_usuario = '321',obs_usuario = 'senha alterada' where id_usuario = 7

delete usuario where id_usuario = 7

create table categoria
(
	id_categoria int not null identity primary key,
	nome_categoria varchar(50) not null unique,
	descricao_categoria varchar(255) null,
	obs_categoria varchar(255) null,
	status_categoria varchar(25) not null
)
select * from categoria
--deletando tabela já criada
drop table categoria

insert into categoria
	(nome_categoria,descricao_categoria,obs_categoria,status_categoria)
values
	('Prego','','','Ativo'),
	('Ouro','','','Ativo'),
	('Tilápio','','','Ativo')

create table produto(
	id_produto int not null identity primary key,
	id_categoria_produto int not null,
	id_usuario_produto int not null,
	nome_produto varchar(50) not null unique,
	valor_produto decimal(10,2) not null,
	qtde_produto int not null,
	cadastro_produto smalldatetime not null default getdate(),
	descricao_produto varchar(255) null,
	tamanho_produto decimal(10,2) not null,
	unidademedida_produto varchar(5) not null,
	obs_produto varchar(255) null,
	status_produto varchar(25) not null
	
	constraint FK_ID_Categoria_Produto foreign key(id_categoria_produto) references categoria(id_categoria),
	constraint FK_ID_Usuario_Produto foreign key(id_usuario_produto) references usuario(id_usuario)
)
drop table produto
select * from produto

insert into produto
(id_categoria_produto,id_usuario_produto,nome_produto,valor_produto,qtde_produto,descricao_produto,tamanho_produto,unidademedida_produto,obs_produto,status_produto)
values
(3,8,'Bala',1.5,10,'',10,'mm','','Ativo')

select * from categoria
select * from usuario

delete usuario where id_usuario = 8

drop table usuario

create table cidade
(
	id_cidade int identity not null primary key,
	nome_cidade varchar(50) not null 
)

--drop table cidade

select * from cidade

insert into cidade (nome_cidade) values
('Piracicaba'),
('Praia Grande'),
('Ribeirão Preto'),
('Sumaré'),
('Barueri'),
('São José dos Campos'),
('Guarulhos'),
('Itaquaquecetuba'),
('Ribeirão Preto'),
('Presidente Prudente'),
('Marília'),
('Marília'),
('Osasco'),
('Taboão da Serra'),
('Campinas'),
('Sorocaba'),
('Taubaté'),
('Taboão da Serra'),
('Araraquara'),
('Diadema'),
('Campinas'),
('São Bernardo do Campo'),
('Piracicaba'),
('Hortolândia'),
('Campinas'),
('Barueri'),
('Sorocaba'),
('São Paulo'),
('Presidente Prudente'),
('Osasco'),
('Marília'),
('São Paulo'),
('Campinas'),
('Ribeirão Preto'),
('Itapevi'),
('Mogi das Cruzes'),
('Rio Claro'),
('Taubaté'),
('Rio Claro'),
('Sumaré'),
('Bauru'),
('São José do Rio Preto'),
('Presidente Prudente'),
('Guarulhos'),
('São Paulo'),
('Mauá'),
('Ribeirão Preto'),
('São José do Rio Preto'),
('Osasco'),
('Barueri'),
('Jacareí'),
('Itapevi'),
('Ribeirão Preto'),
('Ribeirão Preto'),
('Taboão da Serra'),
('Piracicaba'),
('Osasco'),
('Franca'),
('São Vicente'),
('Santo André'),
('Guarulhos'),
('Ribeirão Preto'),
('Rio Claro'),
('Praia Grande'),
('Suzano'),
('Hortolândia'),
('Hortolândia'),
('Sorocaba'),
('Franca'),
('São José do Rio Preto'),
('Guarujá'),
('Itapevi'),
('Indaiatuba'),
('Guarujá'),
('Presidente Prudente'),
('Hortolândia'),
('Barueri'),
('Cotia'),
('Santo André'),
('São Vicente'),
('Jacareí'),
('São Bernardo do Campo'),
('Presidente Prudente'),
('Sumaré'),
('São Carlos'),
('Sorocaba'),
('Presidente Prudente'),
('Bauru'),
('Americana'),
('Hortolândia'),
('São Vicente'),
('Osasco'),
('Guarujá'),
('Taubaté'),
('Piracicaba'),
('Cotia'),
('Presidente Prudente'),
('Itaquaquecetuba'),
('Praia Grande'),
('São José dos Campos'),
('Suzano'),
('Santos'),
('Carapicuíba'),
('São Bernardo do Campo'),
('Santos'),
('Taubaté'),
('São Paulo'),
('Indaiatuba'),
('Campinas'),
('Taboão da Serra'),
('Rio Claro'),
('Hortolândia'),
('São José do Rio Preto'),
('Franca'),
('Guarujá'),
('Franca'),
('Piracicaba'),
('Osasco'),
('Indaiatuba'),
('Ribeirão Preto'),
('Carapicuíba'),
('Rio Claro'),
('Taboão da Serra'),
('Presidente Prudente'),
('São Bernardo do Campo'),
('São Paulo'),
('Cotia'),
('Americana'),
('Sumaré'),
('Guarulhos'),
('Ribeirão Preto'),
('Rio Claro'),
('Rio Claro'),
('Presidente Prudente'),
('Guarujá'),
('Itapevi'),
('Franca'),
('Diadema'),
('Indaiatuba'),
('Piracicaba'),
('Carapicuíba'),
('Cotia'),
('Franca'),
('Taubaté'),
('Diadema'),
('Piracicaba'),
('Presidente Prudente'),
('Embu das Artes'),
('Indaiatuba'),
('Franca'),
('Indaiatuba'),
('Embu das Artes'),
('Araraquara'),
('Ribeirão Preto'),
('Itapevi'),
('Jundiaí'),
('Diadema'),
('Itapevi'),
('Rio Claro'),
('Bauru'),
('Sumaré'),
('São Paulo'),
('Osasco'),
('Mauá'),
('São José do Rio Preto'),
('Sumaré'),
('Taubaté'),
('Suzano'),
('Cotia'),
('Embu das Artes'),
('Praia Grande'),
('Diadema'),
('Jacareí'),
('Osasco'),
('São Vicente'),
('São Vicente'),
('São Carlos'),
('Araraquara'),
('Americana'),
('Americana'),
('Carapicuíba'),
('Praia Grande'),
('Taboão da Serra'),
('Americana'),
('Taboão da Serra'),
('Carapicuíba'),
('Sumaré'),
('Taboão da Serra'),
('São Bernardo do Campo'),
('Mauá'),
('Barueri'),
('São José do Rio Preto'),
('Mauá'),
('Itaquaquecetuba'),
('Barueri'),
('Itaquaquecetuba'),
('Guarujá'),
('Americana'),
('São Paulo'),
('Taubaté'),
('São Vicente'),
('Cotia'),
('Carapicuíba'),
('São Bernardo do Campo'),
('Rio Claro'),
('São Carlos'),
('Diadema'),
('Marília'),
('Embu das Artes'),
('Embu das Artes'),
('Jacareí'),
('Araraquara'),
('Taubaté'),
('Cotia'),
('Bauru'),
('Marília'),
('Barueri'),
('Limeira'),
('Praia Grande'),
('Itaquaquecetuba'),
('Franca'),
('Jundiaí'),
('Piracicaba'),
('Marília'),
('Taboão da Serra'),
('Rio Claro'),
('Piracicaba'),
('Santo André'),
('Guarujá'),
('Bauru'),
('Barueri'),
('Diadema'),
('Franca'),
('Taboão da Serra'),
('Taboão da Serra'),
('Barueri'),
('Carapicuíba'),
('Hortolândia'),
('Americana'),
('Franca'),
('Itapevi'),
('Itapevi'),
('Jundiaí'),
('Marília'),
('Cotia'),
('Taubaté'),
('Limeira'),
('São Vicente'),
('São José dos Campos'),
('Embu das Artes'),
('Itapevi'),
('Rio Claro'),
('São Paulo'),
('São Vicente'),
('Bauru'),
('Indaiatuba'),
('Campinas'),
('Marília'),
('Araraquara'),
('São Paulo'),
('Barueri'),
('Itapevi'),
('São Vicente'),
('São Bernardo do Campo'),
('Barueri'),
('Mogi das Cruzes'),
('Rio Claro'),
('São José dos Campos'),
('Jundiaí'),
('Taubaté'),
('Presidente Prudente'),
('São Vicente'),
('São Paulo'),
('Americana'),
('Americana'),
('Suzano'),
('Itapevi'),
('Hortolândia'),
('Rio Claro'),
('Marília'),
('Sorocaba'),
('São Vicente'),
('Araraquara'),
('Praia Grande'),
('Sorocaba'),
('Limeira'),
('Cotia'),
('Piracicaba'),
('Marília'),
('Araraquara'),
('Rio Claro'),
('Indaiatuba'),
('Ribeirão Preto'),
('Piracicaba'),
('Piracicaba'),
('Carapicuíba'),
('Cotia'),
('Americana'),
('Mogi das Cruzes'),
('Santos'),
('Araraquara'),
('Marília'),
('Limeira'),
('Rio Claro'),
('São Vicente'),
('Sorocaba'),
('Mogi das Cruzes'),
('São José do Rio Preto'),
('Itaquaquecetuba'),
('São Vicente'),
('Embu das Artes'),
('Ribeirão Preto'),
('Guarujá'),
('Itaquaquecetuba'),
('Rio Claro'),
('Presidente Prudente'),
('Embu das Artes'),
('São José do Rio Preto'),
('Campinas'),
('Itapevi'),
('Taboão da Serra'),
('Ribeirão Preto'),
('Franca'),
('Campinas'),
('Santos'),
('Suzano'),
('São José do Rio Preto'),
('Praia Grande'),
('Santo André'),
('Diadema'),
('Limeira'),
('Ribeirão Preto'),
('Bauru'),
('Barueri'),
('Indaiatuba'),
('Mauá'),
('Piracicaba'),
('Embu das Artes'),
('Guarujá'),
('Santo André'),
('São Bernardo do Campo'),
('São Vicente'),
('São Vicente'),
('Suzano'),
('Suzano'),
('Piracicaba'),
('Jacareí'),
('Ribeirão Preto'),
('Santo André'),
('Presidente Prudente'),
('Mauá'),
('Piracicaba'),
('Taubaté'),
('Taubaté'),
('Sorocaba'),
('Rio Claro'),
('Carapicuíba'),
('Santo André'),
('Santos'),
('Piracicaba'),
('Presidente Prudente'),
('Americana'),
('Mogi das Cruzes'),
('Piracicaba'),
('Taubaté'),
('São Carlos'),
('Barueri'),
('Guarujá'),
('Sorocaba'),
('Mauá'),
('Mauá'),
('Carapicuíba'),
('Taubaté'),
('Presidente Prudente'),
('Embu das Artes'),
('Ribeirão Preto'),
('São José dos Campos'),
('Sumaré'),
('São Bernardo do Campo'),
('São José do Rio Preto'),
('Taboão da Serra'),
('Americana'),
('Indaiatuba'),
('Hortolândia'),
('Sumaré'),
('Mogi das Cruzes'),
('Araraquara'),
('Itapevi'),
('Sorocaba'),
('Carapicuíba'),
('Presidente Prudente'),
('Americana'),
('São Bernardo do Campo'),
('Barueri'),
('Piracicaba'),
('Limeira'),
('Jacareí'),
('Jundiaí'),
('São Vicente'),
('Cotia'),
('Taubaté'),
('Mogi das Cruzes'),
('Mogi das Cruzes'),
('Presidente Prudente'),
('São José dos Campos'),
('Guarulhos'),
('Limeira'),
('Mauá'),
('Presidente Prudente'),
('Araraquara'),
('Indaiatuba'),
('Araraquara'),
('São Vicente'),
('Marília'),
('São Carlos'),
('São Vicente'),
('Praia Grande'),
('Mauá'),
('Presidente Prudente'),
('Diadema'),
('Indaiatuba'),
('Araraquara'),
('Campinas'),
('Suzano'),
('Praia Grande'),
('Diadema'),
('Taboão da Serra'),
('Carapicuíba'),
('Jacareí'),
('Embu das Artes'),
('Hortolândia'),
('Mogi das Cruzes'),
('Barueri'),
('Sorocaba'),
('Jundiaí'),
('Araraquara'),
('São Carlos'),
('Campinas'),
('Santo André'),
('Embu das Artes'),
('Campinas'),
('São Bernardo do Campo'),
('Piracicaba'),
('Marília'),
('Santos'),
('Suzano'),
('Sumaré'),
('São Vicente'),
('São Paulo'),
('Indaiatuba'),
('Ribeirão Preto'),
('Praia Grande'),
('Itapevi'),
('Diadema'),
('Campinas'),
('Carapicuíba'),
('Sorocaba'),
('Ribeirão Preto'),
('Santos'),
('São Carlos'),
('Diadema'),
('Barueri'),
('Diadema'),
('Mauá'),
('Piracicaba'),
('Guarujá'),
('São José dos Campos'),
('Rio Claro'),
('São Paulo'),
('São Vicente'),
('Rio Claro'),
('Jacareí'),
('São Paulo'),
('São Vicente'),
('Taubaté'),
('Marília'),
('São Vicente'),
('Bauru'),
('Itapevi'),
('Taboão da Serra'),
('Mogi das Cruzes'),
('São Paulo'),
('Guarujá'),
('Santos'),
('Itaquaquecetuba'),
('Santo André'),
('Piracicaba'),
('Araraquara'),
('Franca'),
('Hortolândia'),
('Guarulhos'),
('Marília'),
('Osasco'),
('Indaiatuba'),
('Guarujá'),
('Presidente Prudente'),
('São Bernardo do Campo'),
('São Bernardo do Campo'),
('Taubaté'),
('Mauá'),
('Carapicuíba'),
('Indaiatuba'),
('Sorocaba'),
('Guarulhos'),
('Guarujá'),
('Indaiatuba'),
('Diadema'),
('Sumaré'),
('São José do Rio Preto'),
('Marília'),
('São Vicente'),
('Sorocaba'),
('Osasco'),
('Diadema'),
('São Bernardo do Campo'),
('Presidente Prudente'),
('Itapevi'),
('Limeira'),
('Itaquaquecetuba'),
('São José dos Campos'),
('Sumaré'),
('Rio Claro'),
('Campinas'),
('Mauá'),
('Hortolândia'),
('São Bernardo do Campo'),
('Jundiaí'),
('São Vicente'),
('Bauru'),
('Itapevi'),
('Barueri'),
('Americana'),
('Taboão da Serra'),
('Piracicaba'),
('Praia Grande'),
('Diadema'),
('São José dos Campos'),
('Osasco'),
('Ribeirão Preto'),
('Santo André'),
('Osasco'),
('Carapicuíba'),
('Guarujá'),
('Limeira'),
('Santos'),
('Bauru'),
('Rio Claro'),
('Ribeirão Preto'),
('São José dos Campos'),
('São Vicente'),
('São Bernardo do Campo'),
('Araraquara'),
('Limeira'),
('Cotia'),
('Rio Claro'),
('Ribeirão Preto'),
('São Paulo'),
('São Vicente'),
('Suzano'),
('Bauru'),
('Taubaté'),
('Cotia'),
('Mogi das Cruzes'),
('Sumaré'),
('Cotia'),
('Franca'),
('Carapicuíba'),
('Limeira'),
('São José dos Campos'),
('Osasco'),
('São Paulo'),
('Taboão da Serra'),
('Hortolândia'),
('Santo André'),
('Araraquara'),
('Marília'),
('Guarujá'),
('Diadema'),
('Franca'),
('Diadema'),
('São Bernardo do Campo'),
('Ribeirão Preto'),
('Presidente Prudente'),
('Jacareí'),
('Araraquara'),
('Embu das Artes'),
('Bauru'),
('Mogi das Cruzes'),
('Ribeirão Preto'),
('Santos'),
('São José do Rio Preto'),
('Bauru'),
('Itaquaquecetuba'),
('Presidente Prudente'),
('São José dos Campos'),
('Itapevi'),
('Osasco'),
('Diadema'),
('São Paulo'),
('Itaquaquecetuba'),
('Mauá'),
('Embu das Artes'),
('Campinas'),
('Taboão da Serra'),
('Cotia'),
('Presidente Prudente'),
('São José dos Campos'),
('Mogi das Cruzes'),
('Barueri'),
('Taboão da Serra'),
('Carapicuíba'),
('Araraquara'),
('Taboão da Serra'),
('Barueri'),
('Mauá'),
('Diadema'),
('Rio Claro'),
('Guarulhos'),
('Santo André'),
('São José do Rio Preto'),
('Itaquaquecetuba'),
('Sumaré'),
('Cotia'),
('Guarujá'),
('Sumaré'),
('São Bernardo do Campo'),
('São Bernardo do Campo'),
('Suzano'),
('Rio Claro'),
('Limeira'),
('Marília'),
('Ribeirão Preto'),
('Praia Grande'),
('Mauá'),
('São Bernardo do Campo'),
('Sumaré'),
('Campinas'),
('Sumaré'),
('Sumaré'),
('Jundiaí'),
('Araraquara'),
('Campinas'),
('Limeira'),
('Guarulhos'),
('São José dos Campos'),
('Itaquaquecetuba'),
('Ribeirão Preto'),
('Itapevi'),
('São José do Rio Preto'),
('Bauru'),
('Sorocaba'),
('São Vicente'),
('Itaquaquecetuba'),
('Suzano'),
('Piracicaba'),
('Campinas'),
('Osasco'),
('Santo André'),
('Jacareí'),
('Guarujá'),
('Jundiaí'),
('Presidente Prudente'),
('Barueri'),
('Carapicuíba'),
('Ribeirão Preto'),
('Praia Grande'),
('São Vicente'),
('Embu das Artes'),
('Suzano'),
('Taubaté'),
('Piracicaba'),
('Hortolândia'),
('Bauru'),
('São José dos Campos'),
('Santo André'),
('Embu das Artes'),
('Americana'),
('Santo André'),
('Jundiaí'),
('Americana'),
('Bauru'),
('Piracicaba'),
('Mauá'),
('Itaquaquecetuba'),
('Presidente Prudente'),
('Suzano'),
('Bauru'),
('Guarulhos'),
('Sumaré'),
('Indaiatuba'),
('Marília'),
('Presidente Prudente'),
('Santo André'),
('São Paulo'),
('Franca'),
('Cotia'),
('Diadema'),
('São Paulo'),
('Santos'),
('Itaquaquecetuba'),
('Sumaré'),
('Osasco'),
('Bauru'),
('Limeira'),
('Mauá'),
('Limeira'),
('Cotia'),
('São Bernardo do Campo'),
('Guarulhos'),
('Itaquaquecetuba'),
('Guarujá'),
('Santo André'),
('Taboão da Serra'),
('Bauru'),
('Americana'),
('Itapevi'),
('São José dos Campos'),
('Itaquaquecetuba'),
('Sorocaba'),
('Piracicaba'),
('Indaiatuba'),
('Indaiatuba'),
('Hortolândia'),
('Ribeirão Preto'),
('Santos'),
('Franca'),
('Praia Grande'),
('Itaquaquecetuba'),
('Guarujá'),
('Americana'),
('Osasco'),
('Hortolândia'),
('Jacareí'),
('Hortolândia'),
('Jacareí'),
('São José dos Campos'),
('Guarujá'),
('Mauá'),
('São Paulo'),
('Taboão da Serra'),
('Guarujá'),
('São Bernardo do Campo'),
('São José do Rio Preto'),
('Taubaté'),
('Rio Claro'),
('Campinas'),
('Taubaté'),
('Mogi das Cruzes'),
('Sorocaba'),
('Jundiaí'),
('Rio Claro'),
('Americana'),
('Indaiatuba'),
('São Carlos'),
('Suzano'),
('São Vicente'),
('São José do Rio Preto'),
('Carapicuíba'),
('Rio Claro'),
('Suzano'),
('Bauru'),
('Presidente Prudente'),
('Jundiaí'),
('Osasco'),
('São José do Rio Preto'),
('Franca'),
('São José do Rio Preto'),
('Itaquaquecetuba'),
('São José dos Campos'),
('Osasco'),
('Ribeirão Preto'),
('Ribeirão Preto'),
('Araraquara'),
('Piracicaba'),
('Indaiatuba'),
('São Bernardo do Campo'),
('Itaquaquecetuba'),
('Carapicuíba'),
('Barueri'),
('Araraquara'),
('Santo André'),
('Taubaté'),
('Limeira'),
('Jacareí'),
('Itaquaquecetuba'),
('Bauru'),
('Rio Claro'),
('São Vicente'),
('Diadema'),
('Osasco'),
('Limeira'),
('São José dos Campos'),
('São Vicente'),
('Presidente Prudente'),
('Sorocaba'),
('São Paulo'),
('Sumaré'),
('Sorocaba'),
('Mogi das Cruzes'),
('São Vicente'),
('Embu das Artes'),
('Bauru'),
('Cotia'),
('Mauá'),
('São Vicente'),
('Limeira'),
('Hortolândia'),
('São Carlos'),
('Campinas'),
('Cotia'),
('Bauru'),
('Sorocaba'),
('Mauá'),
('Embu das Artes'),
('Cotia'),
('Franca'),
('Ribeirão Preto'),
('São Paulo'),
('Jacareí'),
('Limeira'),
('Mauá'),
('Mauá'),
('Guarujá'),
('Mogi das Cruzes'),
('Diadema'),
('Taboão da Serra'),
('Franca'),
('Praia Grande'),
('São Carlos'),
('São Vicente'),
('Rio Claro'),
('Presidente Prudente'),
('Jundiaí'),
('Sorocaba'),
('Campinas'),
('Carapicuíba'),
('São Paulo'),
('Jundiaí'),
('Mogi das Cruzes'),
('Barueri'),
('Hortolândia'),
('São José do Rio Preto'),
('Mauá'),
('Guarujá'),
('Araraquara'),
('Suzano'),
('Franca'),
('Santos'),
('Barueri'),
('Hortolândia'),
('Barueri'),
('Embu das Artes'),
('Guarujá'),
('Itapevi'),
('São Carlos'),
('São Carlos'),
('Itaquaquecetuba'),
('Osasco'),
('Suzano'),
('Campinas'),
('Americana'),
('Jacareí'),
('Praia Grande'),
('Osasco'),
('Praia Grande'),
('Praia Grande'),
('São Carlos'),
('Rio Claro'),
('Carapicuíba'),
('Osasco'),
('São José do Rio Preto'),
('Rio Claro'),
('São José do Rio Preto'),
('Guarujá'),
('Itaquaquecetuba'),
('Piracicaba'),
('Jacareí'),
('Santo André'),
('São Bernardo do Campo'),
('São Paulo'),
('Limeira')
